#--CHALLENGE JOINING ON MULTIPLE TABLES
#Write SQL queries to perform the following tasks using the Sakila database:

#List the number of films per category.

select
	c.name as name_cateogry,
    #f.title as film_title,
    count(f.title) as films_per_category
from sakila.category as c
join sakila.film_category as fc
	on c.category_id = fc.category_id
join sakila.film as f
	on f.film_id = fc.film_id
group by c.name
order by films_per_category desc;

#Retrieve the store ID, city, and country for each store.


select
	s.store_id,
    c.city as city_name,
    cy.country as country_name
from sakila.store as s
join sakila.address as a
	on s.address_id = a.address_id
join sakila.city as c
	on a.city_id = c.city_id
join sakila.country as cy
	on c.country_id = cy.country_id;

#Calculate the total revenue generated by each store in dollars.


select
    s.store_id,
    sum(p.amount) reveneu_per_store
from sakila.payment as p
join sakila.staff as s
	on p.staff_id = s.staff_id
group by s.store_id;

#Determine the average running time of films for each category.
select
	c.name as name_cateogry,
    #f.title as film_title,
    avg(f.length) as average_film_length_per_category
from sakila.category as c
join sakila.film_category as fc
	on c.category_id = fc.category_id
join sakila.film as f
	on f.film_id = fc.film_id
group by c.name
order by average_film_length_per_category desc;
